server:
  servlet:
    context-path: /testes
  port: 1216
spring:
  application:
    name: testes
  data:
    elasticsearch:
      cluster-name: es-cluster
      cluster-nodes: 106.13.90.178:9300
      repositories:
        enabled: true
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
#    # 正式
#    host: 106.13.90.178
#    port: 6379
#    password: 123456
#    # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
#    timeout: 10s
#    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
#    jedis:
#      pool:
#        # 最大空闲连接数
#        max-idle: 50
#        # 最小空闲连接数
#        min-idle: 5
#        # 等待可用连接的最大时间，负数为不限制
#        max-wait:  -1s
#        # 最大活跃连接数，负数为不限制
#        max-active: -1
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      db-type: mysql
      id-type: 2 #auto
      field-strategy: 2 #not_empty
      table-underline: true
      capital-mode: true
      column-underline: false
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
sharding:
  jdbc:
    datasource:
      names: membership
      membership:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://106.13.90.178:3306/membership?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
        username: root
        password: 6May2019@
    config:
      sharding:
        tables:
          mem_position:
            actual-data-nodes: membership.mem_position_$->{0..7}
            table-strategy:
              standard:
                sharding-column: COMPANY_ID
                precise-algorithm-class-name: com.testes.config.ModuloShardingTableAlgorithm
            key-generator-column-name: ID
            key-generator-class-name: io.shardingsphere.core.keygen.DefaultKeyGenerator
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql